### ISSUE TITLE
Restructure Games

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#116]
RTD:
 - When a game is modified, the database updates that game data in the database
 - After a games data is updated in the database, that change is reflected in the game object
 - DB stays in 3rd Normal Form

**Comment by sradms0** [comment]
All Games References throughout Program use one of the two DB connection styles provided in https://docs.google.com/document/d/1Z6VcVdzqU-V98eja8L9mVqp-t4314HkTWEPYfxfTAq4/edit?usp=sharing

**Comment by AmeliaChady** [comment]
I need to look through code.

**Comment by Rmelikyan** [comment]
Real Time: 6h

**Comment by sradms0** [comment]
1h
