### ISSUE TITLE
Restructure Developers

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#117]
RTD:
 - When a developer is modified, the database updates that developer data in the database
 - After a developer's data is updated in the database, that change is reflected in the developer object
 - Database stays in 3rd Normal Form

**Comment by sradms0** [comment]
All references to developers use style in
https://docs.google.com/document/d/1Z6VcVdzqU-V98eja8L9mVqp-t4314HkTWEPYfxfTAq4/edit?usp=sharing

**Comment by kerryannebuckman** [comment]
40 min:
 - modified developer class to use string gameName instead of a game.

**Comment by kerryannebuckman** [comment]
30 min: 
 - load and save dev in sqliteSource

**Comment by kerryannebuckman** [comment]
schema covered in another card
