### ISSUE TITLE
Restructure GameLists

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#118]
RTD:
 - When a GameList is modified, the database updates that GameLists data in the database
 - After a GameLists's data is updated in the database, that change is reflected in the GameLists object
 - Database 3rd Normal Form

**Comment by sradms0** [comment]
GameLists references all use one style in
https://docs.google.com/document/d/1Z6VcVdzqU-V98eja8L9mVqp-t4314HkTWEPYfxfTAq4/edit?usp=sharing

**Comment by sradms0** [comment]
180 Minutes
