### ISSUE TITLE
Account Object

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#132]
RTD:
Can Create Account Object

**Comment by kerryannebuckman** [comment]
- email, id, password

**Comment by kerryannebuckman** [comment]
40 min:
- account constructor
- isEmailValidTest (from previous s.e. project)
- account test passes
- isEmailValid passes (implementation from previous s.e. project)

**Comment by AmeliaChady** [comment]
Need Username & Password Qualifications

**Comment by kerryannebuckman** [comment]
1 hr:
- isUsernameValid, test and implementation
- isPasswordValid, test and implementation
- isCharacterValid, test and implementation

**Comment by kerryannebuckman** [comment]
Stuck:
- I just realized isUsernameValid and isEmailValid should check the username and email don't exist yet
