### ISSUE TITLE
Create Developer Account

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#134]
RTD:
 - a developer account can be created through the ui
 - the new account is saved to the database after.

**Comment by sradms0** [comment]
Stuck since an account needs to be inserted into the database before it can be created.

**Comment by sradms0** [comment]
1 hour (~90% complete, includes small option menu creation)

**Comment by kerryannebuckman** [comment]
30 min:
- createAccount in UI
