### ISSUE TITLE
Add Game to Wishlist

### ISSUE THREAD

**Issue by Rmelikyan** [AmeliaChady/TheBigGirlGameBrowser#14]
RTD:
 - a game can be added to the user's wishlist
 - a game that has a status of only 'accepted' can be added
 - a game cannot be added to if it is already in the wishlist
 - a game cannot be added if it is already in the user's game list
 - the count of numberInWishlist in game is updated

**Comment by kelseyryangrant** [comment]
took 2 hours to complete

**Comment by kerryannebuckman** [comment]
waste
