### ISSUE TITLE
Create the Review class

### ISSUE THREAD

**Issue by kerryannebuckman** [AmeliaChady/TheBigGirlGameBrowser#15]
RTD:
 - has properties:
   - author
   - review id
   - game title
   - rating (1-5)
   - summary (1-10000 characters)
 - A review can be created

**Comment by kerryannebuckman** [comment]
30 min
- constructor test
- constructor

**Comment by kerryannebuckman** [comment]
40 min: 
-adding authors, ids

**Comment by kerryannebuckman** [comment]
40 min: 
-adding authors, ids

**Comment by AmeliaChady** [comment]
Completed as waste in Sprint 2

**Comment by AmeliaChady** [comment]
.5 Hours
