### ISSUE TITLE
GamebrowserLogin

### ISSUE THREAD

**Issue by Rmelikyan** [AmeliaChady/TheBigGirlGameBrowser#192]
- Called by UI
- Arguments: username and password strings
- Return: Tuple (UserAcct or NULL, DeveloperAcct or Null)

- This will be used by UI Login function such that based on the scraped Username and Passwords it will receive the userAcct, devAcct, neither, or both!
- If both, then active user can decide how to proceed
- if neither, call gamebrowser.LoadAdmin() and move on.

**Comment by AmeliaChady** [comment]
1.5 hours
