### ISSUE TITLE
User can update a review

### ISSUE THREAD

**Issue by kerryannebuckman** [AmeliaChady/TheBigGirlGameBrowser#219]
RTD:
- when looking at a game, users will have the ability to update the summary or rating of their review through the UI
-calls gameBrowser's update review methods

**Comment by kerryannebuckman** [comment]
30 min

**Comment by kelseyryangrant** [comment]
3hrs

**Comment by kerryannebuckman** [comment]
Waste^ never made it to master. Didn't see the branch and there was no pull request so I just did it, hence my first comment. Sorry for my lack of communication
