### ISSUE TITLE
A Developer Object

### ISSUE THREAD

**Issue by AmeliaChady** [AmeliaChady/TheBigGirlGameBrowser#38]
RTD:
- A developer object that contains:
   - A Name
   - A List of Games (enum for what the gameStatus is)

**Comment by kerryannebuckman** [comment]
30 min:
 - Wrote constructor test
 - Wrote constructor to pass tests (name of developer and gameList)

**Comment by kerryannebuckman** [comment]
Why I'm stuck:
Should the enum go in game?
